apiVersion: v1
kind: PersistentVolume
metadata:
        name: theia-pv04
spec:
        accessModes:
                - ReadWriteOnce
        capacity:
                storage: 3Gi
        persistentVolumeReclaimPolicy: Retain
        storageClassName: keti-theia-pv-04
        nfs:
                server: 10.0.2.192
                path: /pv/keti/auth/01/workspace/
apiVersion: v1
kind: PersistentVolume
metadata:
        name: theia-dind-pv04
spec:
        accessModes:
                - ReadWriteOnce
        capacity:
                storage: 15Gi
        persistentVolumeReclaimPolicy: Retain
        storageClassName: keti-theia-dind-pv-04
        nfs:
                server: 10.0.2.192
                path: /pv/keti/auth/01/dind-workspace/
