apiVersion: v1
kind: Service
metadata:
        name: rook-ceph-theia-service01
        namespace: rook-ceph-example
spec:
        selector:
                app.kubernetes.io/name: rook-ceph-theia-deploy01
        type: NodePort
        ports:
                - protocol: TCP
                  port: 3000
                  targetPort: 3000
