apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: keti-theia-dind-pvc-03
        namespace: keti-product
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 15Gi
        storageClassName: keti-theia-ide-sc