apiVersion: v1
kind: Service
metadata:
        name: theia-ingress-service04
        namespace: keti-product
spec:
        selector:
                app.kubernetes.io/name: theia-deploy04
        type: ClusterIP
        ports:
                - protocol: TCP
                  port: 30125
                  targetPort: 3000
