apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia-deploy04
  namespace: keti-product
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: theia-deploy04
  template:
    metadata:
      labels:
        app.kubernetes.io/name: theia-deploy04
    spec:
      containers:
      - name: keti-theia
        image: gwangyong/enhanced-keti-theia-ide:1.1.7
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nfs-pv-04
          mountPath: /home/theia/workspace
        env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
      - name: docker
        image: docker:27.0-dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: "tcp://0.0.0.0:2375"
      volumes:
      - name: nfs-pv-04
        persistentVolumeClaim:
          claimName: theia-pvc-04
      - name: dind-storage
        persistentVolumeClaim:
                claimName: keti-theia-dind-pvc-04
